document.writeln("<nav class=\'navbar navbar-default\'>");
document.writeln("  <div class=\'container\'>");
document.writeln("    <div class=\'navbar-header\'>");
document.writeln(" <a class=\'navbar-brand hidden-xs\'>您好，欢迎访问金金汇，请先</a>");
document.writeln("        <a class=\'index_login hidden-xs\' href=\'#\'>登录</a>");
document.writeln("        <a class=\'index_login hidden-xs\'>/</a>");
document.writeln("        <a class=\'index_login hidden-xs\' href=\'#\'>注册</a>");
document.writeln("        </div>");
document.writeln("    <div class=\'collapse navbar-collapse\' id=\'bs-example-navbar-collapse-1\'>");
document.writeln("      <ul class=\'nav navbar-nav navbar-right\' style=\'font-size:13px;\'>");
document.writeln("        <li class=\'dropdown\'>");
document.writeln("          <a href=\'#\' class=\'dropdown-toggle\' data-toggle=\'dropdown\' role=\'button\' aria-expanded=\'false\'>个人中心 <span class=\'caret\'></span></a>");
document.writeln("          <ul class=\'dropdown-menu\' role=\'menu\' style=\'font-size:13px;\'>");
document.writeln("            <li><a href=\'#\'>我的主页</a></li>");
document.writeln("            <li><a href=\'#\'>我的收藏</a></li>");
document.writeln("            <li><a href=\'#\'>我的发布</a></li>  ");
document.writeln("      </ul>");
document.writeln("          </li>");
document.writeln("        <li><a href=\'#\'>帮助中心</a></li>");
document.writeln("      </ul>");
document.writeln("    </div>");
document.writeln("     <div class=\'collapse navbar-collapse \' id=\'bs-example-navbar-collapse-2\'>");
document.writeln("      <ul class=\'nav navbar-nav navbar-right visible-xs\'>");
document.writeln("        <li>");
document.writeln("         <div class=\'input-group\'>");
document.writeln("       <input class=\'form-control\' type=\'text\'>");
document.writeln("    <span class=\'input-group-btn\'>");
document.writeln("      <button class=\'btn btn-primary\' type=\'button\'>搜索</button>");
document.writeln("    </span>");
document.writeln("  </div>");
document.writeln("          </li>");
document.writeln("      </ul>");
document.writeln("    </div>");
document.writeln("    </div>");
document.writeln("</nav>");